ITECH/ITECH/ITECH/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from musicial import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name='index'),
    path('musicial/',include('musicial.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ITECH/ITECH/musicial/urls.py
from django.urls import path
from musicial import views

app_name ='musicial'

urlpatterns = [
    path('',views.index,name='index'),
    path('signin',views.signInPage,name='signin'),
    path('register',views.registerPage,name='register'),
    path('landing',views.userHomepage,name='landing'),
    path('create-post',views.userCreatePostPage,name='create-post'),
    path('social',views.userSocialPage,name='social'),
    path('profile',views.userProfilePage,name='profile'),
    path('songs',views.songPage,name='songs'),
    path('playlist',views.userPlaylistPage,name='playlist'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('delete/<int:id>', views.delete, name='delete'),
]

ITECH/ITECH/musicial/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from datetime import datetime
import uuid

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    age = models.IntegerField(blank=False)
    gender = models.CharField(max_length=50,blank=False)
    picture = models.ImageField(upload_to='profile_images',blank=False)

    def __str__(self):
        return self.user.username

class FriendProfile(models.Model):
    user = models.ForeignKey(UserProfile,on_delete=models.CASCADE,related_name='target_user')
    friend = models.ManyToManyField(UserProfile,related_name='target_friend')

    def __str__(self):
        return self.user.user.username
    
    def get_num_friends(self):
        return self.friend.count()

class FriendRequest(models.Model):
    sender = models.ForeignKey(UserProfile,on_delete=models.CASCADE,related_name='friend_send')
    receiver = models.ForeignKey(UserProfile,on_delete=models.CASCADE,related_name='friend_receive')

    def __str__(self):
        return self.sender.user.username + '<-->' + self.receiver.user.username
    
class Post(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    user = models.ForeignKey(UserProfile,on_delete=models.CASCADE,related_name='user_post')
    picture = models.ImageField(upload_to='posts',blank=False)
    caption = models.CharField(max_length=200,blank=True,default='')
    date = models.DateField(default=datetime.now())
    likes = models.ManyToManyField(UserProfile,related_name='post_likes')

    def __str__(self):
        return self.user.user.username + ':' + self.caption
    
    def get_date(self):
        return datetime.strftime(self.date,"%a, %b %d, %Y")
    
    def total_likes(self):
        return self.likes.count()

class Comment(models.Model):
    post = models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    name = models.CharField(max_length=512,blank=False)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.caption,self.name)


#any form field validators

ITECH/ITECH/musicial/forms.py
from django import forms
from django.contrib.auth.models import User
from musicial.models import UserProfile

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','email','password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('age','gender','picture')

ITECH/ITECH/musicial/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login
from musicial.forms import UserForm, UserProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from musicial.models import UserProfile, FriendProfile, Post, Comment, FriendRequest
from django.views.decorators.csrf import csrf_exempt
import base64
import requests
from datetime import date
from django.template import loader
# Create your views here.

def index(request):
    return render(request,'musicial/homepage.html')

def signInPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
            if user.check_password(password):
                user = authenticate(username=username,password=password)
                if user:
                    if user.is_active:
                        login(request,user)
                        return HttpResponseRedirect('landing')
                    else:
                        return HttpResponse("Your Musicial account does not exist")
                else:
                    return HttpResponse('Invalid login details')
            else:
                return HttpResponse('Wrong Password')
        except User.DoesNotExist:
            return HttpResponse('Invalid login details')
        
    else:
        return render(request,'musicial/sign-in.html')

def registerPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
            if user:
                return HttpResponse('User already exists')
        except User.DoesNotExist:
            user_form = UserForm(request.POST)
            profile_form = UserProfileForm(request.POST,request.FILES)

            if user_form.is_valid() and profile_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()

                profile = profile_form.save(commit=False)
                profile.user = user

                if 'picture' in request.FILES:
                    print('Picture acquired')
                    profile.picture = request.FILES['picture']
                profile.save()

                user = authenticate(username=username,password=password)
                login(request,user)
                return HttpResponseRedirect('landing')
            else:
                print(user_form.errors,profile_form.errors)
    else:
        return render(request,'musicial/registerPage.html')

@csrf_exempt
def userHomepage(request):
    if request.method == 'POST':
        type_of_request = request.POST['type']
        picture_id = request.POST['picture_id']
        print('Got ',picture_id)
        post = Post.objects.get(id=picture_id)
        if type_of_request == 'like':
            post.likes.add(UserProfile.objects.get(user=request.user))
            return JsonResponse({'likes':str(post.total_likes())+' likes'})
        else:
            #add the new comment
            com = Comment.objects.create(post=post,name=request.user.username,body=request.POST['comment'])
            #retrieve all comments
            comms = Comment.objects.filter(post=post)
            comments = [c.name+' '+c.date_added.strftime("%a %m %y")+' '+c.body+'\n' for c in comms]
            return JsonResponse({'comments':''.join(comments)})
    else:
        #get posts of friends and send to frontend for displaying
        current_user = UserProfile.objects.get(user=request.user)
        current_user_friends = FriendProfile.objects.get(user=current_user)
        posts = [Post.objects.filter(user=f) for f in current_user_friends.friend.all()]
        posts = [p for post in posts for p in post.all()]
        context_dict = {'posts':[]}
        for post in posts:
            comments = [c.name+' '+c.date_added.strftime("%a %m %y")+' '+c.body+'\n' for c in Comment.objects.filter(post=post)]
            context_dict['posts'].append({
                        'id':post.id,
                        'username':post.user.user.username,
                        'time':post.get_date(),
                        'picture':post.picture,
                        'caption':post.caption,
                        'likes': str(post.total_likes()) + ' likes',
                        'comments':''.join(comments)
                    })
        return render(request,'musicial/userhomepage.html',context=context_dict)

def userCreatePostPage(request):
    return render(request,'musicial/createPage.html')

@csrf_exempt
def userSocialPage(request):
    context_dict = {'requests':[]}
    if request.method == 'POST':
        if 'friending' in request.POST.keys():
            #create new friend request
            user = UserProfile.objects.get(user=User.objects.get(username=request.POST['friending']))
            f_req = FriendRequest.objects.create(sender=UserProfile.objects.get(user=request.user),receiver=user)
        if 'accept' in request.POST.keys():
            #accept friend request
            user1, user2 = UserProfile.objects.get(user=User.objects.get(username=request.POST['accept'])), UserProfile.objects.get(user=request.user)
            friendlist1, friendlist2 = FriendProfile.objects.get_or_create(user=user1)[0], FriendProfile.objects.get_or_create(user=user2)[0]
            friendlist1.friend.add(user2)
            friendlist2.friend.add(user1)
            FriendRequest.objects.filter(sender=UserProfile.objects.get(user=User.objects.get(username=request.POST['accept'])),receiver=UserProfile.objects.get(user=request.user)).delete()
        if 'reject' in request.POST.keys():
            #reject friend request
            FriendRequest.objects.filter(sender=UserProfile.objects.get(user=User.objects.get(username=request.POST['reject'])),receiver=UserProfile.objects.get(user=request.user)).delete()
            
        friend_query = request.POST.get('friend-query')
        try:
            user = User.objects.get(username=friend_query)
            user = UserProfile.objects.get(user=user)
            current_friendlist = FriendProfile.objects.filter(user=UserProfile.objects.get(user=request.user))
            is_friend = False
            for f in current_friendlist[0].friend.all():
                if user.user.username == f.user.username: # check if friend is already in friendlist
                    is_friend = True
                    break
            check_req_sent  = FriendRequest.objects.filter(sender=UserProfile.objects.get(user=request.user),receiver=user)
            check_req_received = FriendRequest.objects.filter(sender=user,receiver=UserProfile.objects.get(user=request.user))

            if is_friend:
                context_dict['status'] = 'Friend'
                context_dict['request_to'] = user
            elif check_req_received.count() != 0: #incoming request from user pending
                context_dict['status'] = 'Received'
                context_dict['request_to'] = user
            elif check_req_sent.count() == 0: # found user to send request
                context_dict['status'] = 'Display'
                context_dict['request_to'] = user
            else: # request already sent
                context_dict['status'] = 'Sent'
                context_dict['request_to'] = user
        except User.DoesNotExist:
            context_dict['status'] = 'Invalid'
    
    #see how many friend requests current user has received
    current_user = UserProfile.objects.get(user=request.user)
    received_requests = [FriendRequest.objects.filter(receiver=current_user)]
    received_requests = [fq for req in received_requests for fq in req.all()]
        
    for req in received_requests:
        context_dict['requests'].append({
                'username':req.sender.user.username,
                'picture':req.sender.picture
            })
    #get the friends of the current user
    current_user_friends = FriendProfile.objects.get(user=current_user)
    friends = [f for f in current_user_friends.friend.all()]
    context_dict['friends'] = friends
    return render(request,'musicial/socialPage.html',context=context_dict)

def userProfilePage(request):
    #get no. of friends
    current_user = UserProfile.objects.get(user=request.user)
    current_user_friends = FriendProfile.objects.get(user=current_user)
    context_dict = {'num_friends':current_user_friends.get_num_friends(),'posts':[]}
    #get posts of user
    posts = [Post.objects.filter(user=current_user)]
    posts = [p for post in posts for p in post.all()]
    for post in posts:
            comments = [c.name+' '+c.date_added.strftime("%a %m %y")+' '+c.body+'\n' for c in Comment.objects.filter(post=post)]
            context_dict['posts'].append({
                        'id':post.id,
                        'username':post.user.user.username,
                        'time':post.get_date(),
                        'picture':post.picture,
                        'caption':post.caption,
                        'likes': str(post.total_likes()) + ' likes',
                        'comments':''.join(comments)
                    })
    return render(request,'musicial/ProfilePage.html',context=context_dict)

def songPage(request):
    #Spotify authorization
    client_id = '350eb16772f243f2a403853b013ed7fe' # Your client id
    client_secret = 'c3440e5b15ce4277a6eb63dd075818bb' # Your secret

    auth_url = 'https://accounts.spotify.com/api/token'
    auth_str = '{}:{}'.format(client_id, client_secret)
    b64_auth_str = base64.b64encode(auth_str.encode()).decode('utf-8')
    headers = {
            'Authorization': 'Basic ' + b64_auth_str
        }
    payload = {

ITECH/ITECH/templates/musicial/PlaylistPage.html
{% extends 'musicial/base.html' %}
{% load staticfiles %}

{% block style_block %}
<link rel="stylesheet" type="text/css" href="{% static 'css/userPlaylistpageStyle.css' %}"/>
{% endblock %}

{% block nav_block %}
        <!-- nav buttons under the Profile-pic -->
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
          <a class="nav-link" href="{% url 'musicial:landing' %}" aria-selected="true"><i class="bi bi-house"></i> Home</a>
          <a class="nav-link" href="{% url 'musicial:profile' %}" aria-selected="false"><i class="bi bi-person-badge"></i> Profile</a>
          <a class="nav-link" href="{% url 'musicial:create-post' %}" aria-selected="false"><i class="bi bi-plus-circle"></i> Create</a>
          <a class="nav-link" href="{% url 'musicial:social' %}" aria-selected="false"><i class="bi bi-people-fill"></i> Social</a>
          <a class="nav-link" href="{% url 'musicial:songs' %}" aria-selected="true"><i class="bi bi-music-note"></i>Songs</a>
          <a class="nav-link active" href="{% url 'musicial:playlist' %}" aria-selected="false"><i class="bi bi-music-note-list"></i> Playlist</a>
          <a class="nav-link" href="{% url 'musicial:logout' %}" aria-selected="false"><i class="bi bi-box-arrow-left"></i> Logout</a>
        </div>
{% endblock %}

      <!--right part-->
{% block content_block %}
      <div style="margin-top: 30px; margin-bottom: 50px;">
        <!--nav tabs of "Playlist Creation" and "Playlists"-->
        <ul class="nav nav-tabs nav-justified">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#menu1">Create Playlist</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#menu2">Playlist</a>
          </li>       
       </ul>
       <div class="tab-content">
        <div class="tab-pane container active" id="menu1">
          <form method="POST" action="{% url 'musicial:playlist' %}">
            {% csrf_token %}
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <label class="col-sm-3 text-align" >Playlist </label>
              </div>
              <input type="text" class="form-control" placeholder="Playlist name" name="playlist" id="playlist" required>
            </div>
            <!--submit button-->
            <button type="submit" class="btn btn-primary">submit</Inp></button> 
          </form>
          {% if status %}
          {% if status == 'Created' %}
            <h4>Playlist successfully created</h4>
          {% else %}
            <h4>Playlist already exists</h4>
          {% endif %}
          {% endif %}
        </div>
        <div class="tab-pane container" id="menu2">
          <!-- choice of playlist-->
      <div class="d-flex justify-content-center">
        <div class="btn-group col-md-5">
           <!-- button group content here -->
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                Playlists
                </button>
                <div class="dropdown-menu col-sm-11 text-center">
                  {% for playlist in playlists %}
                  <button class="dropdown-item playlist" type="button" id="{{ playlist }}" value="{{ playlist }}">{{ playlist }}</button>
                  <div class="dropdown-divider"></div>
                  {% endfor %}
                  </div>
                </div>
      </div>
      <br>

      <!--Playlist songs-->
      <ul class="list-group" id="songs-list">
        
        
        
      </ul>
      
      
  </div>
        </div>
       </div>
      
{% endblock %}

{% block script_block %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'js/playlist.js' %}"></script>
{% endblock %}

ITECH/ITECH/templates/musicial/ProfilePage.html
{% extends 'musicial/base.html' %}
{% load staticfiles %}

{% block style_block %}
<link rel="stylesheet" type="text/css" href="{% static 'css/userprofilepageStyle.css' %}"/>
{% endblock %}

{% block nav_block %}
        <!-- nav buttons under the Profile-pic -->
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
          <a class="nav-link" href="{% url 'musicial:landing' %}" aria-selected="true"><i class="bi bi-house"></i> Home</a>
          <a class="nav-link active" href="{% url 'musicial:profile' %}" aria-selected="false"><i class="bi bi-person-badge"></i> Profile</a>
          <a class="nav-link" href="{% url 'musicial:create-post' %}" aria-selected="false"><i class="bi bi-plus-circle"></i> Create</a>
          <a class="nav-link" href="{% url 'musicial:social' %}" aria-selected="false"><i class="bi bi-people-fill"></i> Social</a>
          <a class="nav-link" href="{% url 'musicial:songs' %}" aria-selected="true"><i class="bi bi-music-note"></i>Songs</a>
          <a class="nav-link" href="{% url 'musicial:playlist' %}" aria-selected="false"><i class="bi bi-music-note-list"></i> Playlist</a>
          <a class="nav-link" href="{% url 'musicial:logout' %}" aria-selected="false"><i class="bi bi-box-arrow-left"></i> Logout</a>
        </div>
{% endblock %}

{% block content_block %}
    <img src="{{ user.userprofile.picture.url }}" alt="img-fluid Profile Picture" class="Profile-pic rounded-circle mx-auto d-block">

    <div class="d-flex justify-content-center">
        <h4 class="text-dark">{{ user.username }}</h4>
    </div>

    <div class="d-flex justify-content-between mb-3">
        <h4 class="text-dark follow">{{ num_friends }} friends</h4>
    </div>

    <hr>

    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          {% for post in posts %}
          {% if forloop.counter0 == 0 %}
          <div class="carousel-item active">
            <div class="card Post-card">
              <div class="row">
                
                    <div class="col-md-6">
                      <div class="card-header">
                        <p class="card-text"><small class="text-muted">{{ post.time }}</small></p>
                      </div>
                      
                      <img class="card-img-top" src="{{ post.picture.url }}" alt="{{ forloop.counter0 }} slide">
                      
                      <p class="card-text">{{ post.caption }} </p>
                    
                      <div class="card-footer">
                      <p id="likes{{ post.id }}">{{ post.likes }}</p>
                    </div>
                    </div>
                  
                      <div class="col-md-6">
                          <div class="card-body">
                          <p id="comments{{ post.id }}">{{ post.comments }}</p>
                        </div>
                      </div>
                    
                  </div>
                  </div>
          </div>
          {% else %}
          <div class="carousel-item">
            <div class="card Post-card">
              <div class="row">
                
                    <div class="col-md-6">
                      <div class="card-header">
                        <p class="card-text"><small class="text-muted">{{ post.time }}</small></p>
                      </div>
                      
                      <img class="card-img-top" src="{{ post.picture.url }}" alt="{{ forloop.counter0 }} slide">
                      
                      <p class="card-text">{{ post.caption }} </p>
                    
                      <div class="card-footer">
                      <p id="likes{{ post.id }}">{{ post.likes }}</p>
                    </div>
                    </div>
                  
                      <div class="col-md-6">
                          <div class="card-body">
                          <p id="comments{{ post.id }}">{{ post.comments }}</p>
                        </div>
                      </div>
                    
                  </div>
                  </div>
            
          </div>
          {% endif %}
          {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
  {% endblock %}

ITECH/ITECH/templates/musicial/createPage.html
{% extends 'musicial/base.html' %}
{% load staticfiles %}

{% block style_block %}
<link rel="stylesheet" type="text/css" href="{% static 'css/usercreatepageStyle.css' %}"/>
{% endblock %}

{% block nav_block %}
        <!-- nav buttons under the Profile-pic -->
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
          <a class="nav-link" href="{% url 'musicial:landing' %}" aria-selected="true"><i class="bi bi-house"></i> Home</a>
          <a class="nav-link" href="{% url 'musicial:profile' %}" aria-selected="false"><i class="bi bi-person-badge"></i> Profile</a>
          <a class="nav-link active" href="{% url 'musicial:create-post' %}" aria-selected="false"><i class="bi bi-plus-circle"></i> Create</a>
          <a class="nav-link" href="{% url 'musicial:social' %}" aria-selected="false"><i class="bi bi-people-fill"></i> Social</a>
          <a class="nav-link" href="{% url 'musicial:songs' %}" aria-selected="true"><i class="bi bi-music-note"></i>Songs</a>
          <a class="nav-link" href="{% url 'musicial:playlist' %}" aria-selected="false"><i class="bi bi-music-note-list"></i> Playlist</a>
          <a class="nav-link" href="{% url 'musicial:logout' %}" aria-selected="false"><i class="bi bi-box-arrow-left"></i> Logout</a>
        </div>
{% endblock %}
      <!--the right part: to upload photos and music-->
      
{% block content_block %}
   
             <form method="POST" action="{% url 'musicial:create-post' %}" enctype="multipart/form-data">
              {% csrf_token %}
            <!-- upload function -->
            <div class="container"> 
              <div class="header">
                
                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> 
                <path d="M7 10V9C7 6.23858 9.23858 4 12 4C14.7614 4 17 6.23858 17 9V10C19.2091 10 21 11.7909 21 14C21 15.4806 20.1956 16.8084 19 17.5M7 10C4.79086 10 3 11.7909 3 14C3 15.4806 3.8044 16.8084 5 17.5M7 10C7.43285 10 7.84965 10.0688 8.24006 10.1959M12 12V21M12 12L15 15M12 12L9 15" stroke="#000000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
              </div>
              <div class="input-group mb-3">
              
              <input type="file" id="image" name='picture' required> 
            </div>
          </div>
            
            <!-- Caption Bar-->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <label class="col-sm-3 text-align" >Caption: </label>
              </div>
              <input id="caption" name="caption" type="text" class="form-control" aria-label="Caption">
            </div>   
            <!--submit button-->
            <button type="submit" class="btn btn-primary">submit</Inp></button>  
          </form>
          {% if status %}
          <h4>Post uploaded successfully!!</h4>
          {% endif %}
{% endblock %}     

ITECH/ITECH/templates/musicial/socialPage.html
{% extends 'musicial/base.html' %}
{% load staticfiles %}

{% block style_block %}
<link rel="stylesheet" type="text/css" href="{% static 'css/usersocialpageStyle.css' %}"/>
{% endblock %}

{% block nav_block %}
        <!-- nav buttons under the Profile-pic -->
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
          <a class="nav-link" href="{% url 'musicial:landing' %}" aria-selected="true"><i class="bi bi-house"></i> Home</a>
          <a class="nav-link" href="{% url 'musicial:profile' %}" aria-selected="false"><i class="bi bi-person-badge"></i> Profile</a>
          <a class="nav-link" href="{% url 'musicial:create-post' %}" aria-selected="false"><i class="bi bi-plus-circle"></i> Create</a>
          <a class="nav-link active" href="{% url 'musicial:social' %}" aria-selected="false"><i class="bi bi-people-fill"></i> Social</a>
          <a class="nav-link" href="{% url 'musicial:songs' %}" aria-selected="true"><i class="bi bi-music-note"></i>Songs</a>
          <a class="nav-link" href="{% url 'musicial:playlist' %}" aria-selected="false"><i class="bi bi-music-note-list"></i> Playlist</a>
          <a class="nav-link" href="{% url 'musicial:logout' %}" aria-selected="false"><i class="bi bi-box-arrow-left"></i> Logout</a>
        </div>
{% endblock %}

      <!--right part-->
{% block content_block %}
        <form class="form-inline" method="POST" action="{% url 'musicial:social' %}">
          {% csrf_token %}
          <div class="form-group">
              <input class="friend-search" type="text" id="friend-search" name="friend-query" placeholder="Search">
          </div>
          <button type="Search" class="btn btn-primary mb-2 btn-sm">Search</button>
      </form>
        <!--nav tabs of "Friend Requests" and "Friend List"-->
          <ul class="nav nav-tabs nav-justified">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#menu1">Friend Requests</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#menu2">Friends</a>
            </li>       
         </ul>
     
      <div class="tab-content">
        <div class="tab-pane container active" id="menu1">
          {% if status %}
          <div class="list_of_search_results">
            <h4 class="display-4 text-center" style="font-size:30px;">Search results</h4>
            {% if status == 'Invalid' %}
            <div class="input-group mb-3">
              <div class="alert alert-primary" role="alert">No such user exists!!</div>
            </div>
            {% elif status == 'Sent' %}
            <div class="input-group mb-3">
              <div class="alert alert-primary" role="alert">Friend request already sent</div>
            </div>
            {% elif status == 'Received' %}
            <div class="input-group mb-3">
              <div class="alert alert-primary" role="alert">{{ request_to.user.username }} already sent you a request</div>
            </div>
            {% elif status == 'Friend' %}
            <div class="input-group mb-3">
              <div class="alert alert-primary" role="alert">{{ request_to.user.username }} is already a friend</div>
            </div>
            {% elif status == 'Me' %}
            <div class="input-group mb-3">
              <div class="alert alert-primary" role="alert">Can't send friend request to yourself</div>
            </div>
            {% else %}
            <div class="input-group mb-3">
              <div class="alert alert-primary" role="alert">
              <h4 class="disp_send">{{ request_to.user.username }}</h4>
              <button class="btn btn-outline-primary send" name="to_send" value="{{ request_to.user.username }}">Send</button>
            </div>
            </div>
            {% endif %}
          </div>
          <hr>
        {% endif %}
          
          
              <!--input group pf friend requests-->
            <div class="list_of_requests">
              <h4 class="display-4 text-center" style="font-size:30px;">Friend Requests</h4>
              <ul class="list-group">
              {% for request in requests %}
              <li class="list-group-item" id="pending{{ request.username }}">
              
                <div class="row">
                <div class="col-sm-4"><h4>{{ request.username }}</h4></div>
                <div class="col-sm-4"><img src="{{ request.picture.url }}" width="100px"></div>
                <div class="col-sm-4">
                
                  <button class="btn btn-primary accept" value="{{ request.username }}">Accept</button>
                  <button class="btn btn-danger reject" value="{{ request.username }}">Reject</button>
                
              </div>
                </div>
              
            </li>
                {% endfor %}
              </ul>
            </div>
          
        </div>
        <div class="tab-pane container fade" id="menu2">
          <!--list of friends-->
          <ul class="list_of_friends list-group">
            {% for friend in friends %}
              <li class="list-group-item">{{ friend.user.username }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
      
      
    {% endblock %}

  {% block script_block %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'js/social.js' %}"></script> 
  {% endblock %}